### PR TITLE
Config scope: dependencyOverrides in Compile (not Test)

### PR DESCRIPTION
**Pull request by htmldoug**
# Problem
Currently we have:
src/main/scala -> jackson-databind 2.7.x
src/test/scala -> jackson-databind 2.9.x

sbt lock chooses the 2.7.x version and sets for all configurations (including `Test`). Our tests which depend on 2.9.x fail since they require a method that does not exist.

```
04:03:19 sbt.ForkMain$ForkError: java.lang.NoClassDefFoundError: com/fasterxml/jackson/databind/deser/std/ReferenceTypeDeserializer
04:03:19 	at java.lang.ClassLoader.defineClass1(Native Method)
04:03:19 	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
04:03:19 	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
04:03:19 	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
04:03:19 	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
04:03:19 	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
04:03:19 	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
04:03:19 	at java.security.AccessController.doPrivileged(Native Method)
04:03:19 	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
04:03:19 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
04:03:19 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
04:03:19 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
04:03:19 	at com.fasterxml.jackson.datatype.guava.GuavaModule.setupModule(GuavaModule.java:55)
04:03:19 	at com.fasterxml.jackson.databind.ObjectMapper.registerModule(ObjectMapper.java:730)
04:03:19 	at com.spotify.docker.client.ObjectMapperProvider.<clinit>(ObjectMapperProvider.java:74)
```

# Solution
This PR restricts the `dependencyOverrides` to only the `Compile` scope, since that seems to be where they're describing.

### CODE REVIEW

**Comment by htmldoug** [comment]
cc: @rallydan

**Comment by htmldoug** [comment]
Build is unhappy.

**Comment by tkawachi** [comment]
Thank you for PR. Cloud you rebase on master branch?

**Comment by htmldoug** [comment]
Done. Thanks, @tkawachi!

Also, this relates to #28. fyi, @stephanos.

**Comment by jtjeferreira** [comment]
after this change if I get in sbt 1.4.1
```
[warn] there are 31 keys that are not used by any other settings/tasks:
[warn]  
[warn] * integrations / Compile / dependencyOverrides
[warn]   +- /home/joao/git/project/modules/integrations/lock.sbt:4
...
```

**Pull request merged**
