### PR TITLE
Migrating to slash syntax

### PR DESCRIPTION
**Pull request by jtjeferreira**
in preparation for sbt 1.5.0 which deprecates in syntax

### CODE REVIEW

**Comment by jtjeferreira** [comment]
since slash syntax is only supported in sbt 1.1, with this change the plugin only supports 0.13.x and 1.1+ versions

**Comment by jtjeferreira** [comment]
@tkawachi this is ready for a review

**Comment by iadcode** [comment]
For sbt 1.5.0, the <key> in <configuration> syntax of 0.13 has been deprecated so it would be great if we can get a release with this change. Much appreciation to both @jtjeferreira and @tkawachi.

**Comment by tkawachi** [comment]
Sorry for slow response. I just published 0.7.0 to sonatype.

**Comment by jtjeferreira** [comment]
> Sorry for slow response. I just published 0.7.0 to sonatype.

No worries @tkawachi and thanks for the release...

**Pull request merged**
