### PR TITLE
Remove InThisBuild since local files are now project level

### PR DESCRIPTION
**Pull request by lhohan**
Remove InThisBuild since lock files are now project level.

Note this also caused issues for us: wrong versions ended up in project lock.sbt file. Removing the InThisBuild fixed it.

### CODE REVIEW

**Comment by usufruct99** [comment]
*bump*

**Comment by htmldoug** [comment]
I've verified that this resolves my issues with multi-project builds.

@tkawachi would you be so kind as to merge and release please? I'd love to delete my fork.

**Comment by tkawachi** [comment]
Sorry for late reply and thank you for contribution. I've published v0.4.1. Please try it. Note that it may take several hours to appear maven central.

**Comment by htmldoug** [comment]
Thanks @tkawachi. I've switched my builds to v0.4.1 and it's working great.
Thanks also to @lhohan for the fix!

**Pull request merged**
